#!/usr/bin/env ruby

def string_to_offset(str)
  n = str.to_i
  map = {
    :M => 30 * 24 * 60 * 60,
    :d => 24 * 60 * 60,
    :h => 60 * 60,
    :m => 60,
    :s => 1
  }
  map.keys.each do |key|
    return n * map[key] if str =~ /#{key.to_s}$/
  end
  n
end

unless ARGV.size == 3
  $stderr.puts "Usage: ./time-warp -1d date"
  $stderr.puts "(See README)"
end

if ARGV[0] == '-o'
  offset = string_to_offset(ARGV[1])
elsif ARGV[0] == '-s'
  offset = Time.at(ARGV[1].to_i).to_i - Time.now.to_i
else
  puts '-o or -s'
end

puts offset

program = ARGV[2]

pid = fork {
  exec "env DYLD_INSERT_LIBRARIES=#{File.join(File.dirname(__FILE__), "time-interpose.dylib")} '#{program}'"
}

File.open("/tmp/offset.#{pid}", "w").write(offset.to_s)
